"""Manifest-backed prompt packs for model-backed pipeline Agents."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from core.model_review.asset_governor_review import model_review_to_asset_governor_assistance
from core.model_review.codex_cli_client import CodexCliReviewConfig, Runner, run_codex_cli_review
from core.model_review.repair_plan_review import model_review_to_repair_plan_candidate
from core.model_review.visual_acceptance_review import model_review_to_visual_acceptance_output
from core.model_review.visual_layout_review import model_review_to_visual_agent_output


PROJECT_ROOT = Path(__file__).resolve().parents[2]
PROMPT_PACK_ROOT = PROJECT_ROOT / "core" / "model_review" / "prompt_packs"
PROMPT_PACK_MANIFEST = PROMPT_PACK_ROOT / "manifest.json"
PIPELINE_MANIFEST = PROJECT_ROOT / "agents" / "pipeline" / "pipeline_manifest.json"


def _read_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"expected JSON object: {path}")
    return payload


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _resolve_project_path(value: str) -> Path:
    path = (PROJECT_ROOT / value).resolve()
    if not path.is_relative_to(PROJECT_ROOT.resolve()):
        raise ValueError(f"prompt pack path escaped project root: {value}")
    return path


def _project_rel(path: Path) -> str:
    return str(path.resolve().relative_to(PROJECT_ROOT.resolve())).replace("\\", "/")


def _registered_pipeline_agent_ids() -> set[str]:
    manifest = _read_json(PIPELINE_MANIFEST)
    agents = manifest.get("agents", [])
    return {
        str(agent.get("agent_id") or agent.get("id"))
        for agent in agents
        if isinstance(agent, dict) and str(agent.get("agent_id") or agent.get("id") or "")
    }


def _load_manifest() -> dict[str, Any]:
    return _read_json(PROMPT_PACK_MANIFEST)


def list_prompt_packs() -> list[str]:
    """Return registered prompt-pack ids from the prompt-pack manifest."""

    manifest = _load_manifest()
    packs = manifest.get("packs", [])
    return [str(pack.get("agentId")) for pack in packs if isinstance(pack, dict) and pack.get("agentId")]


@dataclass(frozen=True)
class PromptPack:
    agent_id: str
    task_type: str
    version: int
    converter: str
    prompt_path: Path
    boundary_rules_path: Path
    negative_examples_path: Path
    input_schema_path: Path
    output_schema_path: Path

    def _input_required_fields(self) -> list[str]:
        schema = _read_json(self.input_schema_path)
        required = schema.get("required", [])
        return [str(field) for field in required] if isinstance(required, list) else []

    def validate_payload(self, payload: dict[str, Any]) -> None:
        missing = [field for field in self._input_required_fields() if field not in payload]
        if missing:
            raise ValueError(f"prompt payload missing required fields for {self.agent_id}: {', '.join(missing)}")

    def render_prompt(self, payload: dict[str, Any]) -> str:
        """Render the full prompt sent to the model-review bridge."""

        self.validate_payload(payload)
        prompt = self.prompt_path.read_text(encoding="utf-8")
        boundary_rules = self.boundary_rules_path.read_text(encoding="utf-8")
        negative_examples = self.negative_examples_path.read_text(encoding="utf-8")
        payload_json = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
        return "\n\n".join(
            [
                prompt.strip(),
                "## Shared Hard Boundaries",
                boundary_rules.strip(),
                "## Negative Examples",
                negative_examples.strip(),
                "## Bridge Metadata",
                (
                    f"- promptPackId: {self.agent_id}\n"
                    f"- promptPackVersion: {self.version}\n"
                    f"- outputSchema: {_project_rel(self.output_schema_path)}\n"
                    f"- export manifest: generated by the local bridge before model invocation.\n"
                    f"- allowed refs: use only the explicit payload and evidenceRefs listed in the input payload.\n"
                    f"- explicit payload policy: do not request whole-repo, whole-output, fullscreen, or unlisted local files.\n"
                    "- Return strict JSON only. The local bridge attaches modelProviderStatus; do not fabricate it.\n"
                    "- Do not expose raw chain-of-thought. Return visible audit fields only: decision, evidenceUsed, "
                    "evidenceMissing, assumptions, alternativesConsidered, blockingReasons, nextRequiredEvidence, "
                    "finalResponseAllowedClaims, learningCandidate, and toolIntent.\n"
                    "- Your JSON must include statePatch, finalResponseAllowedClaims, evidenceUsed, evidenceMissing, "
                    "assumptions, alternativesConsidered, blockingReasons, nextRequiredEvidence, learningCandidate, "
                    "and toolIntent. Set toolIntent to null when you are not requesting a tool. When requesting a "
                    "tool, return a full tool-intent/v1 object; encode nested JSON inputs as payloadJson or auditJson."
                ),
                "## Input Payload",
                f"```json\n{payload_json}\n```",
            ]
        )


def load_prompt_pack(agent_id: str) -> PromptPack:
    """Load and validate one prompt pack by Agent id."""

    manifest = _load_manifest()
    registered_agents = _registered_pipeline_agent_ids()
    packs = manifest.get("packs", [])
    for pack in packs:
        if not isinstance(pack, dict) or str(pack.get("agentId")) != agent_id:
            continue
        if agent_id not in registered_agents:
            raise ValueError(f"prompt pack agent is not registered in pipeline manifest: {agent_id}")
        prompt_pack = PromptPack(
            agent_id=agent_id,
            task_type=str(pack.get("taskType") or agent_id),
            version=int(pack.get("version") or 1),
            converter=str(pack.get("converter") or "identity"),
            prompt_path=_resolve_project_path(str(pack["promptPath"])),
            boundary_rules_path=_resolve_project_path(str(pack["boundaryRulesPath"])),
            negative_examples_path=_resolve_project_path(str(pack["negativeExamplesPath"])),
            input_schema_path=_resolve_project_path(str(pack["inputSchemaPath"])),
            output_schema_path=_resolve_project_path(str(pack["outputSchemaPath"])),
        )
        for path in (
            prompt_pack.prompt_path,
            prompt_pack.boundary_rules_path,
            prompt_pack.negative_examples_path,
            prompt_pack.input_schema_path,
            prompt_pack.output_schema_path,
        ):
            if not path.is_file():
                raise FileNotFoundError(f"prompt pack file missing: {path}")
        return prompt_pack
    raise KeyError(f"unknown prompt pack: {agent_id}")


def _convert_model_review(converter: str, review: dict[str, Any]) -> dict[str, Any]:
    if converter == "visual_acceptance":
        return model_review_to_visual_acceptance_output(review)
    if converter == "visual_layout":
        return model_review_to_visual_agent_output(review)
    if converter == "repair_plan":
        return model_review_to_repair_plan_candidate(review)
    if converter == "asset_governor":
        return model_review_to_asset_governor_assistance(review)
    if converter == "identity":
        return dict(review)
    raise ValueError(f"unknown prompt pack converter: {converter}")


def run_prompt_pack_review(
    *,
    agent_id: str,
    payload: dict[str, Any],
    run_dir: str | Path,
    output_path: str | Path | None = None,
    raw_output_path: str | Path | None = None,
    config: CodexCliReviewConfig | None = None,
    runner: Runner | None = None,
    cwd: str | Path | None = None,
    trace_id: str | None = None,
) -> dict[str, Any]:
    """Run a prompt-pack model review and write converted Agent output."""

    pack = load_prompt_pack(agent_id)
    run_root = Path(run_dir)
    stable_trace_id = trace_id or f"{agent_id}-review"
    trace_dir = run_root / "model_traces" / agent_id / stable_trace_id
    converted_output_path = Path(output_path) if output_path is not None else run_root / "agent_outputs" / f"{agent_id}.json"
    raw_path = (
        Path(raw_output_path)
        if raw_output_path is not None
        else run_root / "agent_outputs" / f"{agent_id}.raw_model_review.json"
    )
    prompt = pack.render_prompt(payload)
    review = run_codex_cli_review(
        prompt=prompt,
        schema_path=pack.output_schema_path,
        output_path=raw_path,
        config=config,
        runner=runner or __import__("subprocess").run,
        cwd=Path(cwd) if cwd is not None else PROJECT_ROOT,
        agent_id=agent_id,
        task_type=pack.task_type,
        trace_id=stable_trace_id,
        trace_dir=trace_dir,
    )
    context = {
        "schemaVersion": "prompt-pack-context/v1",
        "promptPackId": pack.agent_id,
        "promptPackVersion": pack.version,
        "taskType": pack.task_type,
        "converter": pack.converter,
        "schemaPath": _project_rel(pack.output_schema_path),
        "promptPath": _project_rel(pack.prompt_path),
        "inputSchemaPath": _project_rel(pack.input_schema_path),
    }
    _write_json(trace_dir / "prompt_pack_context.json", context)
    converted = _convert_model_review(pack.converter, review)
    _write_json(converted_output_path, converted)
    return converted
